server.port=4000
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/mrrg}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:mrrg}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mrrgpass}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

firebase.service-account-path=${FIREBASE_SERVICE_ACCOUNT_PATH:}
